### ISSUE TITLE
Allow creating new trades

### ISSUE THREAD

**Issue by tysonzero** [jdreaver/oanda-rest-api#7]
I don't really understand how this library can be used to do trading on OANDA, seems like it doesn't let you create new trades or positions or anything. Perhaps some example code will clear up the confusing if I am wrong here.

**Comment by jdreaver** [comment]
[`createOrder`](https://github.com/jdreaver/oanda-rest-api/blob/71d81516b03712b5d61e481586441329ae16b73e/src/OANDA/Orders.hs#L147) is how you create orders, which open positions/trades. Note that I named the modules in line with how OANDA sectioned their documentation. If you need something from the [Order](http://developer.oanda.com/rest-live-v20/order-ep/) section, it will live in [`Orders.hs`](https://github.com/jdreaver/oanda-rest-api/blob/71d81516b03712b5d61e481586441329ae16b73e/src/OANDA/Orders.hs).

Regarding examples: I am not actively working on this library right now. The part of my system that uses it is currently stable and I'm working on other parts. I will definitely come back to this in the future though. OANDA's API can be frustrating to wrap because of all the nullable fields and their poor documentation (wrong field names, incorrectly marking fields as null/non-null when they are the opposite), so it takes some motivation for me to add more endpoints sometimes :smile:

**Comment by tysonzero** [comment]
Ah I see, I was looking at the most recent version on Hackage (for the nicely formatted Haddocks), so 0.3.0.0, which does not have `createOrder`. If the package is stable would you perhaps push 0.4.0.0 to Hackage?

And no worries on the examples, now that my confusion is cleared up I can figure it out just from the types and such, if it's somewhat difficult I will perhaps make a PR with some extra documentation once I get it figured out.

Do you think you will be active enough to accept PR's if I make them? Because I may or may not end up needing to do that, have only looked through the Hackage version so far.

**Comment by jdreaver** [comment]
> Do you think you will be active enough to accept PR's if I make them? Because I may or may not end up needing to do that, have only looked through the Hackage version so far.

Sure thing. As long as you manually test any new endpoints they should be good to go. I can help spot check the endpoint via the docs.

**Comment by tysonzero** [comment]
Awesome! Any chance you will release version 0.4.0.0 to hackage, particularly since you say the current version is stable.
